name: Lint OpenAPI Specification

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest
      
      - name: Lint OpenAPI specification
        run: redocly lint openapi.yml
      
      - name: Bundle OpenAPI specification
        run: redocly bundle openapi.yml --output bundled-openapi.yml
      
      - name: Upload bundled specification
        uses: actions/upload-artifact@v4
        with:
          name: bundled-openapi
          path: bundled-openapi.yml
