name: Lint OpenAPI Specification

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      
      - name: Install Redocly CLI
        run: npm install 
      
      - name: Lint OpenAPI specification
        run: npm run lint
      
      - name: Bundle OpenAPI specification
        run: npm run bundle
      
      - name: Upload bundled specification
        uses: actions/upload-artifact@v4
        with:
          name: bundled-openapi
          path: bundled-openapi.yml
